import React, { useState, useEffect } from 'react';
import { BarChart3, TrendingUp, Users, DollarSign, Activity } from 'lucide-react';
import { reportsApi } from '../api';

// Chart.js imports
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar, Doughnut } from 'react-chartjs-2';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend
);

export default function Analytics() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState('');

  const loadAnalytics = async () => {
    setLoading(true);
    setErrorMsg('');
    try {
      const res = await reportsApi.getAnalytics();
      if (res && res.success !== false) {
        setData(res);
      } else {
        setErrorMsg('Failed to compile reports data.');
      }
    } catch (e) {
      setErrorMsg('Network error fetching analytics details.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAnalytics();
  }, []);

  if (loading) {
    return (
      <div style={styles.loadingContainer}>
        <Activity size={32} className="spin" color="#6366f1" />
        <span>Compiling financial logs...</span>
      </div>
    );
  }

  if (errorMsg) {
    return <div style={styles.alertError}>{errorMsg}</div>;
  }

  const categoryData = data?.revenue_by_category || [];
  const cashierData = data?.cashier_performance || [];

  // Total sales calculation
  const totalRev = categoryData.reduce((acc, c) => acc + parseFloat(c.revenue || 0), 0);
  const totalUnits = categoryData.reduce((acc, c) => acc + parseInt(c.items_sold || 0), 0);

  // Chart configs
  const catChartData = {
    labels: categoryData.map(c => c.category_name),
    datasets: [
      {
        label: 'Revenue (₹)',
        data: categoryData.map(c => c.revenue),
        backgroundColor: '#6366f1',
        borderRadius: 6,
      }
    ]
  };

  const catChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false }
    },
    scales: {
      x: { grid: { display: false }, ticks: { color: '#94a3b8' } },
      y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94a3b8' } }
    }
  };

  const cashierChartData = {
    labels: cashierData.map(c => c.cashier_name),
    datasets: [
      {
        data: cashierData.map(c => c.revenue),
        backgroundColor: ['#10b981', '#6366f1', '#f59e0b', '#ef4444', '#06b6d4'],
        borderWidth: 0,
      }
    ]
  };

  const cashierChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'right',
        labels: { color: '#94a3b8', font: { size: 12 } }
      }
    }
  };

  return (
    <div>
      {/* Aggregated widgets */}
      <div className="dashboard-grid">
        <div className="glass-card" style={styles.miniCard}>
          <div>
            <span style={styles.miniCardLabel}>Total Channel Revenue</span>
            <h2 style={styles.miniCardVal}>₹{totalRev.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</h2>
          </div>
          <div style={{ ...styles.iconBg, backgroundColor: 'rgba(16,185,129,0.12)', color: '#10b981' }}>
            <DollarSign size={20} />
          </div>
        </div>

        <div className="glass-card" style={styles.miniCard}>
          <div>
            <span style={styles.miniCardLabel}>Total Items Distributed</span>
            <h2 style={styles.miniCardVal}>{totalUnits.toLocaleString()} units</h2>
          </div>
          <div style={{ ...styles.iconBg, backgroundColor: 'rgba(99,102,241,0.12)', color: '#6366f1' }}>
            <TrendingUp size={20} />
          </div>
        </div>

        <div className="glass-card" style={styles.miniCard}>
          <div>
            <span style={styles.miniCardLabel}>Active Staff Registered</span>
            <h2 style={styles.miniCardVal}>{cashierData.length} active</h2>
          </div>
          <div style={{ ...styles.iconBg, backgroundColor: 'rgba(245,158,11,0.12)', color: '#f59e0b' }}>
            <Users size={20} />
          </div>
        </div>
      </div>

      {/* Visual charts */}
      <div style={styles.chartsGrid}>
        <div className="glass-card" style={styles.chartBlock}>
          <h3 style={styles.chartTitle}>Revenue Generated by Category</h3>
          <div style={styles.chartContainer}>
            {categoryData.length > 0 ? (
              <Bar data={catChartData} options={catChartOptions} />
            ) : (
              <div style={styles.noData}>No records found</div>
            )}
          </div>
        </div>

        <div className="glass-card" style={styles.chartBlock}>
          <h3 style={styles.chartTitle}>Operator Performance Share</h3>
          <div style={styles.chartContainer}>
            {cashierData.length > 0 ? (
              <Doughnut data={cashierChartData} options={cashierChartOptions} />
            ) : (
              <div style={styles.noData}>No records found</div>
            )}
          </div>
        </div>
      </div>

      {/* Statistics grids */}
      <div style={styles.splitGrid}>
        {/* Category breakdown */}
        <div className="glass-card" style={{ flex: 1.2 }}>
          <h3 style={styles.tableTitle}>Category Financial Performance</h3>
          <div className="table-container">
            {categoryData.length > 0 ? (
              <table className="custom-table">
                <thead>
                  <tr>
                    <th>Category Name</th>
                    <th>Units Sold</th>
                    <th>Total Revenue</th>
                  </tr>
                </thead>
                <tbody>
                  {categoryData.map((cat, idx) => (
                    <tr key={idx}>
                      <td style={{ fontWeight: '600', color: '#fff' }}>{cat.category_name}</td>
                      <td>{cat.items_sold || 0} units</td>
                      <td style={{ fontWeight: '600' }}>₹{parseFloat(cat.revenue || 0).toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <div style={styles.empty}>No category logs recorded.</div>
            )}
          </div>
        </div>

        {/* Cashier breakdown */}
        <div className="glass-card" style={{ flex: 1 }}>
          <h3 style={styles.tableTitle}>Staff Performance Ranks</h3>
          <div className="table-container">
            {cashierData.length > 0 ? (
              <table className="custom-table">
                <thead>
                  <tr>
                    <th>Operator Name</th>
                    <th>Bills Cut</th>
                    <th>Gross Revenue</th>
                  </tr>
                </thead>
                <tbody>
                  {cashierData.map((cash, idx) => (
                    <tr key={idx}>
                      <td style={{ fontWeight: '600', color: '#fff' }}>{cash.cashier_name}</td>
                      <td>{cash.bills_generated} invoices</td>
                      <td style={{ fontWeight: '600', color: '#10b981' }}>₹{parseFloat(cash.revenue || 0).toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <div style={styles.empty}>No operator entries found.</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

const styles = {
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '60vh',
    gap: '1rem',
    color: '#94a3b8',
  },
  alertError: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: '8px',
    padding: '0.75rem 1rem',
    color: '#ef4444',
    marginBottom: '1.5rem',
  },
  miniCard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1.25rem 1.5rem',
  },
  miniCardLabel: {
    fontSize: '0.8rem',
    fontWeight: '600',
    color: '#94a3b8',
    textTransform: 'uppercase',
  },
  miniCardVal: {
    fontSize: '1.6rem',
    color: '#fff',
    fontFamily: "'Outfit', sans-serif",
    marginTop: '0.2rem',
  },
  iconBg: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartsGrid: {
    display: 'grid',
    gridTemplateColumns: '1.3fr 1fr',
    gap: '1.5rem',
    marginBottom: '1.5rem',
  },
  chartBlock: {
    height: '300px',
    display: 'flex',
    flexDirection: 'column',
  },
  chartTitle: {
    fontSize: '1rem',
    color: '#fff',
    marginBottom: '1rem',
    fontFamily: "'Outfit', sans-serif",
  },
  chartContainer: {
    flex: 1,
    position: 'relative',
    height: '100%',
  },
  noData: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: '#64748b',
  },
  splitGrid: {
    display: 'flex',
    gap: '1.5rem',
    flexWrap: 'wrap',
  },
  tableTitle: {
    fontSize: '1.1rem',
    color: '#fff',
    marginBottom: '1rem',
    fontFamily: "'Outfit', sans-serif",
  },
  empty: {
    padding: '2rem',
    textAlign: 'center',
    color: '#64748b',
  },
};
